apiVersion: v1
kind: Service
metadata:
  name: novel-app-canary-service
  labels:
    app: novel-app-canary
    version: canary
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: novel-app-canary
    version: canary